### ISSUE TITLE
陀螺仪的使用

### ISSUE THREAD

**Issue by savamiya** [SJTU-AuTop/RT1064-Code#2]
float diff = 15.8 * sin(angle / 180 * PI * 2.4) / 40 / 2;    这几个数字代表着什么意思

**Comment by C-ZiHao** [comment]
此处sin应为tan，之前忘记修正。angle是舵机转角，2.4是舵机转角与前轮实际转角标定好的的比例系数，40为两倍车长，15.8是使用差速标定后得到的比例关系（也可以直接根据差速公式计算得到）。
